### ISSUE TITLE
기존 레포 이관

### ISSUE THREAD

**Issue by Hwan-seok** [TG-WinG/Meeting-Log#2]
기존에 스터디 진행하려고 만들었던 [레포](https://github.com/T-G-WinG/2019-2-Networking)와 올간이 있어요
별거 없을건데 회장님이 슥한번 보시고 필요한거 있으면 좀 옮겨주세요 삭제 예정입니다
이거 확인하시면 이슈 닫아주세요

@korkeep

**Comment by korkeep** [comment]
행님 감사합니당 😂

마침 2021년에 선배님 초청 강연을 계획중이어서
이참에 지난 자료까지 업로드했습니다.

알려주셔서 감사합니다 선배님 :)

@Hwan-seok
